---
title: "Untitled"
output: html_document
date: "2023-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
d=read.csv(file="D:\\MACHINE LEARNING\\Anyinam\\th\\NHANES.csv",
           header=T,
           sep=",",
           dec=".",
           stringsAsFactors = T)
```

```{r}
view(d)
str(d)
dim(d)
head((d$Gender))
factor(d$Gender)
levels(d$Gender)
```

# Reducing the number of variables

```{r}
require(tidyverse)
dd = 
  d %>% 
  select(Gender,Age,Education,MaritalStatus,Work,HomeRooms,
         Weight,Height,BMI,Testosterone,SmokeNow,RegularMarij,
         PhysActiveDays,SleepHrsNight,SexNumPartnLife,Diabetes)
dd
```
```{r}
summary(dd$BMI)
sd(dd$BMI)  #standard deviation
var(dd$BMI) #variance
IQR(dd$BMI) #interquartile range (difference between 3rd and 1st quartile)
```

```{r}
jpeg("hist_boxplot.jpeg")
par(mfrow=c(1,2))
hist(dd$BMI,col = "wheat") #NB: it implicitly groups data in classes; the modal class is available
boxplot(dd$BMI,col = "wheat")
dev.off()
```

```{r}
dd %>% 
  select(Weight,Height,BMI,Testosterone) %>% 
  drop_na() %>% 
  cor()

```

```{r}
jpeg("BMI_pairs.jpeg")
dd %>% 
  select(Weight,Height,BMI,Testosterone) %>% 
  drop_na() %>%                                
  pairs()

dev.off()

```

```{r}
jpeg("Scatter_plot_tidyverse.jpeg")
par(mfrow=c(2,2))
dd %>% 
  select(Weight,BMI) %>% 
  drop_na %>% 
  plot(pch=19,col="darkblue",cex=0.4)

dd %>% 
  select(Weight,Testosterone) %>% 
  drop_na %>% 
  plot(pch=19,col="darkblue",cex=0.4)

dd %>% 
  select(Weight,Height) %>% 
  drop_na %>% 
  plot(pch=19,col="darkblue",cex=0.4)

dd %>% 
  select(Height,BMI) %>% 
  drop_na %>% 
  plot(pch=19,col="darkblue",cex=0.4)

dev.off()

```

# Quantitative discrete variables

```{r}
head(dd$HomeRooms) 

summary(dd$HomeRooms)
table(dd$HomeRooms) #freq distribution
people_without_HomeRooms=sum(is.na(dd$HomeRooms))
table(dd$HomeRooms)/(length(dd$HomeRooms)-people_without_HomeRooms) #relative frequency distribution 

```

## Frequency distribution table
```{r}
freq_HomeRooms = table(dd$HomeRooms)
jpeg("barplot_home.jpeg")
barplot(freq_HomeRooms,ylab="Frequency",col=rainbow(30)) #Ops, maybe too much colour...
dev.off()
```

## Computing the mode
```{r}
#strategy 1
dd %>% 
  select(HomeRooms) %>% 
  table() %>% 
  which.max() %>% 
  labels()

#strategy 2
which(freq_HomeRooms==max(freq_HomeRooms))[[1]]

#strategy 3
which.max(freq_HomeRooms)[[1]]
```


#### Qualitative variables
```{r}
summary(dd$Work)
table(dd$Work)
```
# Frequency table
```{r}
work_without_na=dd$Work[is.na(dd$Work)==F]
table(work_without_na)/length(work_without_na) #Relative Frequency

```

# Barplot

```{r}
jpeg("barplot_rela_work.jpeg")
barplot(table(work_without_na)/length(work_without_na), col=c("lightgreen", "lightblue", "lightsalmon"),
las=2, cex.names=0.6, cex.axis=0.6, main="Employment status", ylab="Relative Frequency")

dev.off()

```


# Piechart

```{r}
jpeg("piechart_work.jpeg")
pie(table(dd$Work), col=c("lightgreen", "lightblue", "lightsalmon"), cex=0.8)
dev.off()
```

### 3D piechart
```{r}
require(plotrix)
jpeg("3dpiechart.jpeg")
pie3D(table(dd$Work), labels= unlist(labels(table(dd$Work))),
explode=0.1, theta= pi/6, labelcex=0.8, col=c("lightgreen", "lightblue", "lightsalmon"))
dev.off()
```